/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.dialog {
    export class ReviveViewUI extends View {
		public countdownAni:Laya.FrameAnimation;
		public buttonsDownAni:Laya.FrameAnimation;
		public buttonsUpAni:Laya.FrameAnimation;
		public reviveIconBox:Laya.Box;
		public reviveIconList:Laya.List;
		public countdownLabel:Laya.Label;
		public videoButton:Laya.Sprite;
		public shareButton:Laya.Sprite;
		public bottomButtonBox:Laya.Box;
		public skipButton:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("dialog/ReviveView");
        }
    }
    REG("ui.dialog.ReviveViewUI",ReviveViewUI);
}
export module ui.game {
    export class GameSceneUI extends View {
		public background:Laya.Sprite;
		public bg_bottom:Laya.Sprite;
		public front_top:Laya.Sprite;
		public scene3DBox:Laya.Sprite;
		public scoreLabel:Laya.Label;
		public front_bottom:Laya.Sprite;
		public tutorialBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameScene");
        }
    }
    REG("ui.game.GameSceneUI",GameSceneUI);
}
export module ui.home {
    export class HomeViewUI extends View {
		public drawerCloseAni:Laya.FrameAnimation;
		public drawerOpenAni:Laya.FrameAnimation;
		public moreGameOpenAni:Laya.FrameAnimation;
		public moreGameCloseAni:Laya.FrameAnimation;
		public drawerButtonAni:Laya.FrameAnimation;
		public moreGameButtonAni:Laya.FrameAnimation;
		public navigatorBox:Laya.Box;
		public homeIconBox:Laya.Box;
		public homeIconList:Laya.List;
		public moreGameOpenButton:Laya.Sprite;
		public startButton:Laya.Button;
		public drawerBox:Laya.Box;
		public background:Laya.Image;
		public drawerList:Laya.List;
		public drawerCloseButton:Laya.Sprite;
		public drawerOpenButton:Laya.Sprite;
		public moreGameBox:Laya.Box;
		public moreGameCloseButton:Laya.Sprite;
		public moreGameList:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/HomeView");
        }
    }
    REG("ui.home.HomeViewUI",HomeViewUI);
}
export module ui.over {
    export class OverViewUI extends View {
		public restartButtonAni:Laya.FrameAnimation;
		public buttonsDownAni:Laya.FrameAnimation;
		public buttonsUpAni:Laya.FrameAnimation;
		public scoreLabel:Laya.Label;
		public overIconBox:Laya.Box;
		public overIconList:Laya.List;
		public guessLikeBox:Laya.Box;
		public guessLikeList:Laya.List;
		public bottomButtonBox:Laya.Box;
		public homeButton:Laya.Sprite;
		public restartButton:Laya.Sprite;
		public shareButton:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("over/OverView");
        }
    }
    REG("ui.over.OverViewUI",OverViewUI);
}