/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ReviveView from "./script/runtime/ReviveView"
import GameScene from "./script/runtime/GameScene"
import HomeView from "./script/runtime/HomeView"
import Reward from "./script/component/Reward"
import OverView from "./script/runtime/OverView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="showall";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="home/HomeView.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/runtime/ReviveView.ts",ReviveView);
        reg("script/runtime/GameScene.ts",GameScene);
        reg("script/runtime/HomeView.ts",HomeView);
        reg("script/component/Reward.ts",Reward);
        reg("script/runtime/OverView.ts",OverView);
    }
}
GameConfig.init();